# Generated by Django 2.2.7 on 2019-12-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_num', models.CharField(max_length=200)),
                ('liquor_type', models.CharField(max_length=200)),
            ],
        ),
    ]
