# Generated by Django 3.0 on 2019-12-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('idDrink', models.AutoField(primary_key=True, serialize=False)),
                ('strDrink', models.CharField(max_length=100)),
                ('strAlcoholic', models.CharField(max_length=100)),
                ('strInstructions', models.TextField()),
                ('strDrinkThumb', models.URLField()),
                ('strIngredient1', models.CharField(max_length=100)),
                ('strIngredient2', models.CharField(max_length=100)),
                ('strIngredient3', models.CharField(max_length=100)),
                ('strIngredient4', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cocktails',
        ),
    ]
