# Generated by Django 3.0 on 2019-12-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20191209_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='strAlcoholic',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='strDrinkThumb',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='strIngredient1',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='strIngredient2',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='strIngredient3',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='strIngredient4',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='strInstructions',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='idDrink',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
